POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName":"Yo",
  "lastName":"i",
  "email":"yoi10@gmail.com",
  "password":"Elon123456",
  "birthday":"1971-7-28",
  "isMale":true
}